spring.application.name=Chess_Project
server.port=1000
app.page-size=10
spring.datasource.url=jdbc:h2:file:./data/chess;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
