-- ----------------------------------------------------------------------------
-- account: one row per person who registers. Holds only what login needs.
-- (Named "account" rather than "user" because USER is a reserved word in SQL.)
-- ----------------------------------------------------------------------------
CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 1, 2, 3... assigned automatically
    username      VARCHAR(30)  NOT NULL UNIQUE,     -- what they log in with; no two accounts may share one
    email         VARCHAR(100) NOT NULL UNIQUE,     -- for password resets, etc.
    password_hash VARCHAR(100) NOT NULL,            -- a BCrypt hash, NEVER the real password
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,   -- set to FALSE to block an account without deleting it
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ----------------------------------------------------------------------------
-- player_profile: the public, chess-facing side of an account.
-- Exactly one per account: account_id is both this table's key and a link
-- back to account.id, so there can never be two profiles for one account.
-- ----------------------------------------------------------------------------
CREATE TABLE player_profile (
    account_id   BIGINT PRIMARY KEY REFERENCES account(id) ON DELETE CASCADE,  -- delete account => profile goes too
    display_name VARCHAR(50)  NOT NULL,   
    country      VARCHAR(2),                    -- two-letter code, e.g. 'GB'
    rating       INT NOT NULL DEFAULT 1200,     -- everyone starts at 1200
    peak_rating  INT NOT NULL DEFAULT 1200,
    games_played INT NOT NULL DEFAULT 0,
    wins         INT NOT NULL DEFAULT 0,
    draws        INT NOT NULL DEFAULT 0,
    losses       INT NOT NULL DEFAULT 0
);


-- ----------------------------------------------------------------------------
-- user_settings: board preferences, one row per account, same pattern as above.
-- CHECK constraints make the database itself reject nonsense values.
-- ----------------------------------------------------------------------------
CREATE TABLE user_settings (
    account_id       BIGINT PRIMARY KEY REFERENCES account(id) ON DELETE CASCADE,
    board_theme      VARCHAR(30) NOT NULL DEFAULT 'classic',
    show_legal_moves BOOLEAN     NOT NULL DEFAULT TRUE,
    engine_depth     INT         NOT NULL DEFAULT 4 CHECK (engine_depth BETWEEN 1 AND 6)
);


-- ----------------------------------------------------------------------------
-- game_record: one row per finished game.
-- A player column is NULL when that side was the engine. If an account is
-- deleted, its games stay (so the opponent's history survives) but the link
-- is set to NULL.
-- ----------------------------------------------------------------------------
CREATE TABLE game_record (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    white_account_id    BIGINT REFERENCES account(id) ON DELETE SET NULL,
    black_account_id    BIGINT REFERENCES account(id) ON DELETE SET NULL,
    opponent_type       VARCHAR(10) NOT NULL CHECK (opponent_type IN ('HUMAN', 'ENGINE')),
    result              VARCHAR(10) NOT NULL CHECK (result IN ('WHITE_WIN', 'BLACK_WIN', 'DRAW')),
    termination         VARCHAR(20) NOT NULL CHECK (termination IN ('CHECKMATE', 'STALEMATE', 'RESIGNATION')),
    move_list_san       VARCHAR(10000) NOT NULL,   
    final_fen           VARCHAR(100)   NOT NULL,
    white_rating_before INT,                       -- NULL for the engine side / unrated games
    white_rating_after  INT,
    black_rating_before INT,
    black_rating_after  INT,
    played_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes are like a book's index: they make "find all games for player X" fast
-- without scanning every row. Worth it for columns you search by often.
CREATE INDEX idx_game_record_white ON game_record(white_account_id);
CREATE INDEX idx_game_record_black ON game_record(black_account_id);


-- ----------------------------------------------------------------------------
-- rating_history: one row every time a player's rating changes.
-- This is what a "rating over time" graph on the Stats page will read.
-- ----------------------------------------------------------------------------
CREATE TABLE rating_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    game_id     BIGINT REFERENCES game_record(id) ON DELETE SET NULL,  -- which game caused the change
    rating      INT NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rating_history_account ON rating_history(account_id, recorded_at);
